#cloud-config

---
users:
- name: ceccanti
  groups:
  - wheel
  - docker
  coreos-ssh-import-github: andreaceccanti
- name: andreotti
  groups:
  - wheel
  - docker
  coreos-ssh-import-github: dandreotti
write_files:
- path: /etc/sysctl.d/disable_hardlink_protection.conf
  permissions: 0644
  content: |
    fs.protected_hardlinks=0

- path: /home/core/.dockercfg
  owner: core:core
  permissions: 0644
  content: |
        {
          "http://cloud-vm128.cloud.cnaf.infn.it": {
            "auth": "",
            "email": " "
          }
        }

- path: /etc/systemd/system/docker.service.d/50-insecure-registry.conf
  content: |
    [Service]
    Environment=DOCKER_OPTS=--storage-driver=btrfs --insecure-registry="0.0.0.0/0"

- path: /etc/ssl/certs/igi-test-ca.pem
  permissions: 0644
  content: |
    -----BEGIN CERTIFICATE-----
    MIIDgDCCAmigAwIBAgIJAMzDwAv7o5VUMA0GCSqGSIb3DQEBBQUAMC0xCzAJBgNV
    BAYTAklUMQwwCgYDVQQKDANJR0kxEDAOBgNVBAMMB1Rlc3QgQ0EwHhcNMTIwOTI2
    MTUwMDU0WhcNMjIwOTI0MTUwMDU0WjAtMQswCQYDVQQGEwJJVDEMMAoGA1UECgwD
    SUdJMRAwDgYDVQQDDAdUZXN0IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEA9u4Fgtj7YpMRql3NAasEUmP6Byv/CH+dPZNzSxfNCMOPqARLBWS/2Ora
    m5cRpoBByT0LpjDCFBJhLrBKvCvmWOTfS1jYsQwSpC/5scButthlcNOhLKQSZblS
    8Pa7HoFS4zQFwCwWOYbOLF+FblYRgSY30WMi361giydeV8iei8KNH2FIoDyo9kjV
    gYQKp76LFv7urGhc5sHA+HWq7+AfyivtZC+a55Rw6EHXOQ+vih5TPXa1t5RL7IkY
    4U7Ld5ExptBIDx0UkSihYexAY4RGXVUaq535dGtJQ8/NYMrJ5NMGt2X0bRszArnE
    EKc/qdAcgcalgoiaZtVkq45eXADXzwIDAQABo4GiMIGfMB0GA1UdDgQWBBSRdzZ7
    LrRp8yfqt/YIi0ojohFJxjBdBgNVHSMEVjBUgBSRdzZ7LrRp8yfqt/YIi0ojohFJ
    xqExpC8wLTELMAkGA1UEBhMCSVQxDDAKBgNVBAoMA0lHSTEQMA4GA1UEAwwHVGVz
    dCBDQYIJAMzDwAv7o5VUMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEG
    MA0GCSqGSIb3DQEBBQUAA4IBAQB379cvZmfCLvGdoGbW+6ppDNy3pT9hqYmZAlfV
    FGZSEaTKjGCbPuErUNC6+7zhij5CmMtMRhccI3JswjPHPQGm12jiEC492J6Avj/x
    PL8vcBRofe4whXefDVgUw8G1nkQYr2BF0jzeiN72ToISGMbt/q94QV70lYCo/Tog
    UQQ6F+XhztffxQyRgsUXhR4qq1D4h7UifqfQGBzknS23RMLQUdKXG4MhTLMVmxJC
    uY9Oi0It3hk9Qtn0nlZ7rvo5weJGxuRBbZ85Nvw2tIhH7G2osc6zqmHTmUAR4FXb
    l8/ElwGVrURMMuJLDbISVXjBNFuVOS2BdlyEe4x5kfQAWITZ
    -----END CERTIFICATE-----
coreos:
  update:
    reboot-strategy: off
  etcd:
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $public_ipv4
  units:
  - name: update-sysctl.service
    command: start
    content: |
      [Unit]
      Description=Update sysctl values written by cloud-config
      [Service]
      ExecStart=/usr/lib/systemd/systemd-sysctl
  - name: etcd.service
    command: start
  - name: fleet.service
    command: start
  - name: format-ephemeral.service
    command: start
    content: |
      [Unit]
      Description=Formats the ephemeral drive
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/sbin/wipefs -f /dev/vdb
      ExecStart=/usr/sbin/mkfs.btrfs -f /dev/vdb
  - name: create-eph0.service
    command: start
    content: |
      [Unit]
      Description=Create /media/eph0

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/bin/mkdir -p /media/eph0
  - name: var-lib-docker.mount
    command: start
    content: |
      [Unit]
      Description=Mount ephemeral to /var/lib/docker
      Requires=format-ephemeral.service
      After=format-ephemeral.service
      Before=docker.service

      [Mount]
      What=/dev/vdb
      Where=/var/lib/docker
      Type=btrfs
  - name: set-permissions-eph0.service
    command: start
    content: |
      [Unit]
      Description=Change permissions on /media/eph0
      Requires=create-eph0.service
      After=media.eph0.mount
      Before=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/bin/chown docker:docker /media/eph0
      ExecStart=/usr/bin/chmod 775 /media/eph0
  - name: update-ca-certificates.service
    command: start
    content: |
      [Unit]
      Description=Updates ca certificates

      [Service]
      Type=oneshot
      ExecStart=/usr/sbin/update-ca-certificates

  - name: jenkins-slave.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Jenkins slave docker container
      After=docker.service
      Requires=docker.service

      [Service]
      ExecStartPre=-/usr/bin/docker kill jenkins-slave
      ExecStartPre=-/usr/bin/docker rm jenkins-slave
      ExecStartPre=/usr/bin/docker pull cloud-vm128.cloud.cnaf.infn.it/italiangrid/jenkins-slave
      ExecStart=/usr/bin/docker run --name jenkins-slave -p 2222:22 -v /var/run/docker.sock:/var/run/docker.sock -v /media/eph0:/storage:rw -v /home/core/.dockercfg:/home/jenkins/.dockercfg cloud-vm128.cloud.cnaf.infn.it/italiangrid/jenkins-slave
      ExecStop=/usr/bin/docker stop jenkins-slave
      Restart=always

      [Install]
      WantedBy=multi-user.target
